var annotated_dup =
[
    [ "Ui", "namespaceUi.html", [
      [ "MainWindow", "classUi_1_1MainWindow.html", null ]
    ] ],
    [ "visitors", "namespacevisitors.html", [
      [ "back_string_replacer", "structvisitors_1_1back__string__replacer.html", "structvisitors_1_1back__string__replacer" ],
      [ "document_dump", "structvisitors_1_1document__dump.html", "structvisitors_1_1document__dump" ],
      [ "string_extractor_replacer", "structvisitors_1_1string__extractor__replacer.html", "structvisitors_1_1string__extractor__replacer" ]
    ] ],
    [ "back_string_replacer", "structback__string__replacer.html", null ],
    [ "base_node", "structbase__node.html", "structbase__node" ],
    [ "document_dump", "structdocument__dump.html", null ],
    [ "document_node", "structdocument__node.html", "structdocument__node" ],
    [ "DTD_node", "structDTD__node.html", "structDTD__node" ],
    [ "element_node", "structelement__node.html", "structelement__node" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "MyConstants", "classMyConstants.html", "classMyConstants" ],
    [ "MyDatatables", "classMyDatatables.html", "classMyDatatables" ],
    [ "MyLanguageData", "classMyLanguageData.html", "classMyLanguageData" ],
    [ "MyLanguageModel", "classMyLanguageModel.html", "classMyLanguageModel" ],
    [ "MyLingoJobs", "classMyLingoJobs.html", "classMyLingoJobs" ],
    [ "MyLocalization", "classMyLocalization.html", "classMyLocalization" ],
    [ "MyOrgSettings", "classMyOrgSettings.html", "classMyOrgSettings" ],
    [ "MyProjectClass", "classMyProjectClass.html", "classMyProjectClass" ],
    [ "MySqlDbtModel", "classMySqlDbtModel.html", "classMySqlDbtModel" ],
    [ "MyTranlatorParser", "classMyTranlatorParser.html", "classMyTranlatorParser" ],
    [ "QExample", "structQExample.html", "structQExample" ],
    [ "QOnlineTranslator", "classQOnlineTranslator.html", "classQOnlineTranslator" ],
    [ "QOnlineTts", "classQOnlineTts.html", "classQOnlineTts" ],
    [ "QOption", "structQOption.html", "structQOption" ],
    [ "qt_meta_stringdata_MainWindow_t", "structqt__meta__stringdata__MainWindow__t.html", "structqt__meta__stringdata__MainWindow__t" ],
    [ "qt_meta_stringdata_MyDatatables_t", "structqt__meta__stringdata__MyDatatables__t.html", "structqt__meta__stringdata__MyDatatables__t" ],
    [ "qt_meta_stringdata_MyLocalization_t", "structqt__meta__stringdata__MyLocalization__t.html", "structqt__meta__stringdata__MyLocalization__t" ],
    [ "qt_meta_stringdata_MyOrgSettings_t", "structqt__meta__stringdata__MyOrgSettings__t.html", "structqt__meta__stringdata__MyOrgSettings__t" ],
    [ "qt_meta_stringdata_MySqlDbtModel_t", "structqt__meta__stringdata__MySqlDbtModel__t.html", "structqt__meta__stringdata__MySqlDbtModel__t" ],
    [ "qt_meta_stringdata_MyTranlatorParser_t", "structqt__meta__stringdata__MyTranlatorParser__t.html", "structqt__meta__stringdata__MyTranlatorParser__t" ],
    [ "qt_meta_stringdata_QOnlineTranslator_t", "structqt__meta__stringdata__QOnlineTranslator__t.html", "structqt__meta__stringdata__QOnlineTranslator__t" ],
    [ "qt_meta_stringdata_QOnlineTts_t", "structqt__meta__stringdata__QOnlineTts__t.html", "structqt__meta__stringdata__QOnlineTts__t" ],
    [ "QtLingoCase", "classQtLingoCase.html", "classQtLingoCase" ],
    [ "SimpleCrypt", "classSimpleCrypt.html", "classSimpleCrypt" ],
    [ "string_extractor_replacer", "structstring__extractor__replacer.html", null ],
    [ "TranslationFiles", "classTranslationFiles.html", null ],
    [ "TS_node", "structTS__node.html", "structTS__node" ],
    [ "Ui_MainWindow", "classUi__MainWindow.html", "classUi__MainWindow" ],
    [ "Utils", "classUtils.html", "classUtils" ]
];